name       : ruby-domain_name
version    : 0.5.20190701
release    : 4
source     :
    - https://rubygems.org/downloads/domain_name-0.5.20190701.gem : 000a600454cb4a344769b2f10b531765ea7bd3a304fe47ed12e5ca1eab969851
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MPL-2.0
component  : programming.ruby
summary    : RubyGem - domain_name
description: |
    This is a Domain Name manipulation library for Ruby. It can also be used for cookie domain validation based on the Public Suffix List.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby-unf
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
